### ISSUE TITLE
Adding white noise generation function

### ISSUE THREAD

**Issue by johens** [arduino-libraries/Arduino_AdvancedAnalog#76]
Hi! Thank you for your Arduino_AdvancedAnalog library.

I am utilizing it with a Arduino GIGA R1, and would love to find a way to generate white noise instead of the commonly given, and provided functions for sinewave, square wave, triangle wave etc.. 

Is there anyway the library can help with generating white noise? Could be random, or gaussian-distributed..

Thank you!

**Comment by iabdalkader** [comment]
> would love to find a way to generate white noise instead of the commonly given, and provided functions for sinewave, square wave, triangle wave etc..

We don't provide any builtin functions to generate waves. The example just fills a buffer and replays it over and over. You can do the same generate any wave.
