### ISSUE TITLE
Streaming to G711

### ISSUE THREAD

**Issue by edwardruthven** [arduino-libraries/Arduino_AdvancedAnalog#79]
Hi, I am battling to workout the parameter settings required for Arduino Advanced Analog.

```cpp
// Resolution, sample rate, number of samples per channel, queue depth.
if (!adc1.begin(AN_RESOLUTION_16, 8000, 32, 64)) {
  Serial.println("Failed to start analog acquisition!");
  while (1);
}
```

All I know is Ulaw is 14 bit signed and Alaw is 13 bit signed - so what do I use from above.
Also what should I use for samples per channel and queue depth?

**Comment by per1234** [comment]
Hi @edwardruthven. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
